POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc2OTEwMjU5NywidXNlcklkIjoxfQ.lnUYFZq-1J1B4JTnHiP70wK6WfsuOqJi_jhgi1jQAzA

{
    "name": "test event",
    "description": "a test event",
    "location": "a test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}