PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Updated Event",
    "description": "this is updated",
    "location": "a test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}